Image4
distribution-social/SocialDistribution pull request #111
Opened 2023-03-30 02:52 UTC by RonggangCui

2023-04-01 20:50 UTC, jmonteza requested changes

2023-04-01 20:50 UTC, jmonteza commented on socialDistribution/socialDistribution/settings.py
You'll need to set it to True for deployment.

```
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_SSL_REDIRECT = False
```

2023-04-01 22:38 UTC, RonggangCui commented on socialDistribution/socialDistribution/settings.py
Now it is good

2023-04-01 22:39 UTC, RonggangCui commented
This PR is good to go

2023-04-02 06:08 UTC, jmonteza approved these changes

2023-04-02 22:59 UTC, merged